services:
  amneziawg-exporter:
    image: amneziavpn/amneziawg-exporter:2.0.0
    container_name: amneziawg-exporter
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges=true
    network_mode: host
    environment:
      AWG_EXPORTER_OPS_MODE: metricsfile
    volumes:
      - /usr/bin/awg:/usr/bin/awg
      - /tmp/prometheus/:/tmp/prometheus/
